# Generated by Django 4.1.5 on 2023-01-23 16:04

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='resp',
            options={'verbose_name': 'Announcement Response', 'verbose_name_plural': 'Announcement Responses'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
