# Generated by Django 4.1.5 on 2023-02-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_alter_announcement_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resp',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
