# Generated by Django 4.1.5 on 2023-02-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_resp_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('01', 'Танки'), ('02', 'Хилы'), ('03', 'ДД'), ('04', 'Торговцы'), ('05', 'Гилдмастеры'), ('06', 'Квестгиверы'), ('07', 'Кузнецы'), ('08', 'Кожевники'), ('09', 'Зельевары'), ('10', 'Мастера Заклинаний')], default=('01', 'Танки'), max_length=2),
        ),
    ]
