# Generated by Django 4.1.5 on 2023-02-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0004_remove_announcement_category_announcement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('00', 'Танки'), ('01', 'Хилы'), ('02', 'ДД'), ('03', 'Торговцы'), ('04', 'Гилдмастеры'), ('05', 'Квестгиверы'), ('06', 'Кузнецы'), ('07', 'Кожевники'), ('08', 'Зельевары'), ('09', 'Мастера Заклинаний')], default='00', max_length=2),
        ),
    ]
